# google dns:       8.8.8.8
# cloudflare dns:   1.1.1.1
dns_server = "8.8.8.8"

# FORMERR   (1):    The DNS query had a format error.
# SERVFAIL  (2):    The DNS server failed to process the query.
# NXDOMAIN  (3):    The domain name does not exist.
# NOTIMP    (4):    The requested function is not implemented.
# REFUSED   (5):    The server refused to answer the query.
# YXDOMAIN  (6):    The name that should not exist, does exist.
# YXRRSET   (7):    The RRset that should not exist, does exist.
# NXRRSET   (8):    The RRset that should exist, does not exist.
# NOTAUTH   (9):    Server is not authoritative for the zone.
# NOTZONE   (10):   Name not in zone. 
blacklist_response_code = 2 # SERVFAIL


# Support examples:
# *.example.*
# api.example
# api.example.*
# api.example.dp.*
blacklist = ["*.mysite.dp.*", "google.com"]